on:
  pull_request:
    paths:
      - '**/*.md'
      - .github/workflows/lint-markdown.yaml
      - .markdownlint-cli2.jsonc
  push:
    branches:
      - master
    paths:
      - .github/workflows/lint-markdown.yaml
      - '**/*.md'
      - .markdownlint-cli2.jsonc

name: Lint Markdown

jobs:
  lint-md:
    runs-on: ubuntu-latest
    name: markdownlint-cli2
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v22.0.0
        with:
          config: .markdownlint-cli2.jsonc
          globs: '**/*.md'
